export function buildDteFromInvoice(invoice: any) {
  return {
    identificacion: {
      version: '3',
      codigoGeneracion: invoice.generationCode,
      tipoDte: '01',
      numeroControl: 'DTE-001-00000001',
      tipoModelo: 1,
      tipoOperacion: 1,
      tipoContingencia: null,
      motivoContin: null,
      fecEmi: invoice.date ?? new Date().toISOString().split('T')[0],
      horEmi: invoice.transmissionTime,
      tipoMoneda: 'USD',
    },
    emisor: {
      nit: invoice.company.nit,
      nrc: invoice.company.nrc,
      nombre: invoice.company.name,
      codActividad: invoice.company.activityCode ?? '00000',
      descActividad: invoice.company.activityDescription ?? 'Sin descripción',
      nombreComercial: invoice.company.commercialName ?? invoice.company.name,
      telefono: invoice.company.phone ?? '',
      correo: invoice.company.email ?? '',
      codEstableMH: invoice.company.mhCode ?? '000',
      codEstable: invoice.company.localCode ?? '000',
      departamento: invoice.company.department ?? 'San Salvador',
      municipio: invoice.company.municipality ?? 'San Salvador',
      complemento: invoice.company.address ?? '',
    },
    receptor: {
      tipoDocumento: '36',
      numDocumento: invoice.client.nit,
      nombre: invoice.client.name,
      codActividad: invoice.client.activityCode ?? '00000',
      descActividad: invoice.client.activityDescription ?? 'Sin descripción',
      direccion: invoice.client.address ?? '',
      telefono: invoice.client.phone ?? '',
      correo: invoice.client.email ?? '',
      municipio: invoice.client.municipality ?? 'San Salvador',
      departamento: invoice.client.department ?? 'San Salvador',
    },
    cuerpoDocumento: invoice.items.map((item, i) => ({
      numItem: i + 1,
      tipoItem: 1,
      descripcion: item.description,
      cantidad: item.quantity,
      uniMedida: item.unit ?? 'UNI',
      precioUni: item.unitPrice,
      montoDescu: 0,
      ventaNoSuj: 0,
      ventaExenta: 0,
      ventaGravada: item.unitPrice * item.quantity,
      tributos: [],
      psv: 0,
      noGravado: 0,
      ivaItem: +(item.unitPrice * item.quantity * 0.13).toFixed(2),
    })),
    resumen: {
      totalNoSuj: 0,
      totalExenta: 0,
      totalGravada: invoice.subtotal,
      subTotalVentas: invoice.subtotal,
      descuNoSuj: 0,
      descuExenta: 0,
      descuGravada: 0,
      porcDescu: 0,
      totalDescu: 0,
      tributos: [],
      subTotal: invoice.subtotal,
      ivaRete1: 0,
      reteRenta: 0,
      montoTotalOperacion: invoice.total,
      totalNoGravado: 0,
      totalPagar: invoice.total,
      totalLetras: invoice.inWords ?? `${invoice.total} DÓLARES`,
      saldoFavor: 0,
      condiOperacion: 1,
      pagos: [
        {
          codigoPago: 1,
          montoPago: invoice.total,
          plazo: '0 días',
          referencia: 'Pago al contado',
        },
      ],
    },
    extension: {},
    apendice: [],
  };
}
